package com.coding.flavors_types_variants

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import com.coding.flavors_types_variants.ui.theme.FlavorstypesvariantsTheme

/**
 * Entry point for the build-configuration demo app.
 *
 * This sample explains three Android concepts:
 * - Product flavors: business/environment dimensions (for example `tier` and `environment`)
 * - Build types: technical packaging modes (`debug`, `staging`, `release`)
 * - Build variants: one concrete flavor combination plus one build type
 *
 * Example variant in this project: `demoSandboxDebug`.
 */
class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            FlavorstypesvariantsTheme {
                Scaffold(modifier = Modifier.fillMaxSize()) { innerPadding ->
                    VariantInspectorScreen(modifier = Modifier.padding(innerPadding))
                }
            }
        }
    }
}

/**
 * Shows the active flavor/build-type values and the resolved build variant at runtime.
 *
 * The screen intentionally visualizes:
 * - Flavor values from `BuildConfig`
 * - Build type from `BuildConfig`
 * - The final variant name (`flavor + BuildType`)
 * - The full variant matrix generated by the project configuration
 */
@Composable
fun VariantInspectorScreen(modifier: Modifier = Modifier) {
    val variantName = resolveVariantName(BuildConfig.FLAVOR, BuildConfig.BUILD_TYPE)

    Column(
        modifier = modifier
            .fillMaxSize()
            .padding(20.dp),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(
            text = "Build Flavors + Build Types = Build Variant",
            style = MaterialTheme.typography.titleLarge,
            fontWeight = FontWeight.Bold
        )

        VariantBadge(
            tier = BuildConfig.TIER_FLAVOR,
            environment = BuildConfig.ENVIRONMENT_FLAVOR,
            buildType = BuildConfig.BUILD_TYPE_LABEL,
            modifier = Modifier.testTag("variantBadge")
        )
        BuildTypeLegend()

        VariantInfoRow(label = "Flavor dimension `tier`", value = BuildConfig.TIER_FLAVOR)
        VariantInfoRow(label = "Flavor dimension `environment`", value = BuildConfig.ENVIRONMENT_FLAVOR)
        VariantInfoRow(label = "Build type", value = BuildConfig.BUILD_TYPE_LABEL)
        VariantInfoRow(label = "Generated FLAVOR value", value = BuildConfig.FLAVOR)
        VariantInfoRow(label = "Generated BUILD_TYPE value", value = BuildConfig.BUILD_TYPE)
        VariantInfoRow(
            label = "Resolved build variant",
            value = variantName,
            modifier = Modifier.testTag("resolvedVariantRow")
        )

        VariantMatrixCard(variantNames = allVariantNames())

        Text(
            text = "Switch variants from the Build Variants window and run again.",
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.primary
        )
    }
}

@Composable
private fun BuildTypeLegend() {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceContainerLow)
    ) {
        Column(
            modifier = Modifier.padding(12.dp),
            verticalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            Text(
                text = "Build type color legend",
                style = MaterialTheme.typography.labelLarge,
                fontWeight = FontWeight.Bold
            )
            BuildTypeLegendRow(label = "debug", color = Color(0xFF1B4F72))
            BuildTypeLegendRow(label = "staging", color = Color(0xFF7D6608))
            BuildTypeLegendRow(label = "release", color = Color(0xFF145A32))
        }
    }
}

@Composable
private fun BuildTypeLegendRow(label: String, color: Color) {
    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
        Text(
            text = "  ",
            modifier = Modifier
                .size(width = 20.dp, height = 16.dp)
                .background(color = color, shape = MaterialTheme.shapes.extraSmall)
        )
        Text(
            text = label,
            style = MaterialTheme.typography.bodyMedium,
            fontWeight = FontWeight.Medium
        )
    }
}

@Composable
private fun VariantInfoRow(label: String, value: String, modifier: Modifier = Modifier) {
    Card(
        modifier = modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceContainerLow)
    ) {
        Column(modifier = Modifier.padding(12.dp)) {
            Text(text = label, style = MaterialTheme.typography.labelLarge)
            Text(
                text = value,
                style = MaterialTheme.typography.bodyLarge,
                fontWeight = FontWeight.SemiBold
            )
        }
    }
}

/**
 * Renders a compact badge for the active variant.
 *
 * Badge content includes:
 * - Tier marker (`[DEMO]`/`[FULL]`)
 * - Build-type marker (`[DEBUG]`/`[STAGING]`/`[RELEASE]`)
 * - Current `tier | environment | buildType` values
 */
@Composable
private fun VariantBadge(
    tier: String,
    environment: String,
    buildType: String,
    modifier: Modifier = Modifier
) {
    val color = when (buildType) {
        "release" -> Color(0xFF145A32)
        "staging" -> Color(0xFF7D6608)
        else -> Color(0xFF1B4F72)
    }
    val marker = if (tier == "full") "[FULL]" else "[DEMO]"
    val buildTypeToken = "[${buildType.uppercase()}]"

    Text(
        text = "$marker $buildTypeToken  $tier | $environment | $buildType",
        modifier = modifier
            .fillMaxWidth()
            .background(color = color, shape = MaterialTheme.shapes.medium)
            .padding(12.dp),
        color = Color.White,
        style = MaterialTheme.typography.titleMedium,
        fontWeight = FontWeight.Bold
    )
}

@Composable
private fun VariantMatrixCard(variantNames: List<String>) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceContainerLow)
    ) {
        Column(modifier = Modifier.padding(12.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
            Text(
                text = "All possible variants (${variantNames.size})",
                style = MaterialTheme.typography.labelLarge,
                fontWeight = FontWeight.Bold
            )
            Text(
                text = variantNames.joinToString(separator = "\n"),
                fontFamily = FontFamily.Monospace,
                style = MaterialTheme.typography.bodyMedium,
                modifier = Modifier.testTag("variantMatrix")
            )
        }
    }
}

/**
 * Resolves variant naming in the standard Android style:
 * `<flavorCombination><BuildTypeCapitalized>`.
 *
 * Example: `demoSandbox` + `debug` -> `demoSandboxDebug`.
 */
internal fun resolveVariantName(flavor: String, buildType: String): String {
    return "$flavor${buildType.replaceFirstChar(Char::uppercase)}"
}

/**
 * Produces every build variant from this project's matrix.
 *
 * Matrix dimensions:
 * - tier: `demo`, `full`
 * - environment: `sandbox`, `production`
 * - build type: `debug`, `staging`, `release`
 *
 * Total variants: `2 x 2 x 3 = 12`.
 */
internal fun allVariantNames(): List<String> {
    val tiers = listOf("demo", "full")
    val environments = listOf("sandbox", "production")
    val buildTypes = listOf("debug", "staging", "release")

    return tiers.flatMap { tier ->
        environments.flatMap { environment ->
            buildTypes.map { buildType ->
                resolveVariantName("$tier${environment.replaceFirstChar(Char::uppercase)}", buildType)
            }
        }
    }
}

@Preview(showBackground = true)
@Composable
fun VariantInspectorPreview() {
    FlavorstypesvariantsTheme {
        VariantInspectorScreen()
    }
}